apiVersion: v1
kind: Service
metadata:
  name: guestbook
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30080  # You can specify a port or let Kubernetes assign one
  selector:
    app: guestbook
